function renderBlockTrajectoryVideo(result, blockBody, caseConfig, videoDir, bodyRadius)
% 渲染带关键点轨迹的长方体视频。

frameRate = 30;
frameStride = max(1, round(1 / (frameRate * caseConfig.dt)));
frameIds = unique([1:frameStride:numel(result.time), numel(result.time)]);
colors = lines(max(1, size(result.trackedPointHistory, 3)));
axisLimits = computeBlockAxisLimits(result, bodyRadius, caseConfig.axisPadding);
poseTranslationHistory = result.originHistory;

figParams = struct('Name', [result.name, ' trajectory'], 'Width', 18, 'AspectRatio', 0.75);
fig = utils.createFigureA4(figParams);
ax = axes('Parent', fig);
hold(ax, 'on');
grid(ax, 'on');
axis(ax, 'equal');
view(ax, caseConfig.viewAngle(1), caseConfig.viewAngle(2));
xlim(ax, axisLimits(1, :));
ylim(ax, axisLimits(2, :));
if caseConfig.followZWindow
    zWindowCenterHistory = result.rComHistory(3, :);
    zlim(ax, zWindowCenterHistory(1) + 0.5 * caseConfig.zWindowSpan * [-1, 1]);
else
    zlim(ax, axisLimits(3, :));
end
xlabel(ax, 'x (m)');
ylabel(ax, 'y (m)');
zlabel(ax, 'z (m)');

patchHandle = patch( ...
    'Parent', ax, ...
    'Faces', blockBody.faces.', ...
    'Vertices', zeros(size(blockBody.vertices, 2), 3), ...
    'FaceColor', [0.70, 0.70, 0.78], ...
    'FaceAlpha', 0.45, ...
    'EdgeColor', [0.25, 0.25, 0.30], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

comLine = plot3(ax, nan, nan, nan, 'k--', 'LineWidth', 1.0, 'DisplayName', 'Center of mass');
comMarker = plot3(ax, nan, nan, nan, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 5, 'HandleVisibility', 'off');

trackedLineHandles = gobjects(size(result.trackedPointHistory, 3), 1);
trackedMarkerHandles = gobjects(size(result.trackedPointHistory, 3), 1);
for pointIdx = 1:size(result.trackedPointHistory, 3)
    trackedLineHandles(pointIdx) = plot3( ...
        ax, nan, nan, nan, '-', ...
        'Color', colors(pointIdx, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', result.trackedPointNames{pointIdx});
    trackedMarkerHandles(pointIdx) = plot3( ...
        ax, nan, nan, nan, 'o', ...
        'Color', colors(pointIdx, :), ...
        'MarkerFaceColor', colors(pointIdx, :), ...
        'MarkerSize', 5, ...
        'HandleVisibility', 'off');
end

legend(ax, 'Location', 'best');
title(ax, result.name);

videoPath = fullfile(videoDir, caseConfig.videoNames.trajectory);
videoWriter = VideoWriter(videoPath, 'MPEG-4');
videoWriter.FrameRate = frameRate;
if isprop(videoWriter, 'Quality')
    videoWriter.Quality = 95;
end
open(videoWriter);

for frameIdx = frameIds
    worldVertices = hw21utils.transformBodyPoints( ...
        result.rotationHistory(:, :, frameIdx), ...
        poseTranslationHistory(:, frameIdx), ...
        blockBody.vertices ...
    );
    if caseConfig.followZWindow
        zlim(ax, zWindowCenterHistory(frameIdx) + 0.5 * caseConfig.zWindowSpan * [-1, 1]);
    end
    set(patchHandle, 'Vertices', worldVertices.');
    set(comLine, ...
        'XData', result.rComHistory(1, 1:frameIdx), ...
        'YData', result.rComHistory(2, 1:frameIdx), ...
        'ZData', result.rComHistory(3, 1:frameIdx));
    set(comMarker, ...
        'XData', result.rComHistory(1, frameIdx), ...
        'YData', result.rComHistory(2, frameIdx), ...
        'ZData', result.rComHistory(3, frameIdx));

    for pointIdx = 1:size(result.trackedPointHistory, 3)
        pointHistory = result.trackedPointHistory(:, :, pointIdx);
        set(trackedLineHandles(pointIdx), ...
            'XData', pointHistory(1, 1:frameIdx), ...
            'YData', pointHistory(2, 1:frameIdx), ...
            'ZData', pointHistory(3, 1:frameIdx));
        set(trackedMarkerHandles(pointIdx), ...
            'XData', pointHistory(1, frameIdx), ...
            'YData', pointHistory(2, frameIdx), ...
            'ZData', pointHistory(3, frameIdx));
    end

    title(ax, sprintf('%s, t = %.2f s', result.name, result.time(frameIdx)));
    drawnow;
    writeVideo(videoWriter, getframe(fig));
end

close(videoWriter);
close(fig);
end
