function B = inertia_matrix(q2, pi_dyn, params)
% 计算两连杆系统的惯性矩阵。

c2 = cos(q2);
B = [ ...
    params.a(1) * pi_dyn(1) + pi_dyn(2) + (params.a(2) + 2 * params.a(1) * c2) * pi_dyn(3) + pi_dyn(4), ...
    (params.a(2) + params.a(1) * c2) * pi_dyn(3) + pi_dyn(4) + params.k_r2 * pi_dyn(5); ...
    (params.a(2) + params.a(1) * c2) * pi_dyn(3) + pi_dyn(4) + params.k_r2 * pi_dyn(5), ...
    params.a(2) * pi_dyn(3) + pi_dyn(4) + params.k_r2^2 * pi_dyn(5)];
end
